package eu.avalanche7.paradigmrealms.backup;

public enum RestoreManifestStage {
    PREPARED, SERVER_STOPPED_EXPECTED, TARGET_QUARANTINED, REGION_FILES_REWRITTEN,
    OFFLINE_VERIFIED, SERVER_BOOTED, RUNTIME_VERIFIED, COMPLETED, FAILED
}
